# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: catalog.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "catalog.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\rcatalog.proto\x12\x07\x63\x61talog"!\n\x0eGetItemRequest\x12\x0f\n\x07item_id\x18\x01 \x01(\x05"#\n\x0fGetItemsRequest\x12\x10\n\x08item_ids\x18\x01 \x03(\x05"(\n\x14ValidateItemsRequest\x12\x10\n\x08item_ids\x18\x01 \x03(\x05"\xd9\x01\n\x0cItemResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x04 \x01(\t\x12\x12\n\nimage_urls\x18\x05 \x03(\t\x12\x14\n\x0clocation_lat\x18\x06 \x01(\x01\x12\x14\n\x0clocation_lon\x18\x07 \x01(\x01\x12\x10\n\x08owner_id\x18\x08 \x01(\t\x12\x0e\n\x06status\x18\t \x01(\t\x12\x12\n\ncreated_at\x18\n \x01(\t\x12\x12\n\nupdated_at\x18\x0b \x01(\t"O\n\x10GetItemsResponse\x12$\n\x05items\x18\x01 \x03(\x0b\x32\x15.catalog.ItemResponse\x12\x15\n\rnot_found_ids\x18\x02 \x03(\x05"V\n\x0eItemValidation\x12\x0f\n\x07item_id\x18\x01 \x01(\x05\x12\x0e\n\x06\x65xists\x18\x02 \x01(\x08\x12\x11\n\tis_active\x18\x03 \x01(\x08\x12\x10\n\x08owner_id\x18\x04 \x01(\t"E\n\x15ValidateItemsResponse\x12,\n\x0bvalidations\x18\x01 \x03(\x0b\x32\x17.catalog.ItemValidation2\xdc\x01\n\x0e\x43\x61talogService\x12\x39\n\x07GetItem\x12\x17.catalog.GetItemRequest\x1a\x15.catalog.ItemResponse\x12?\n\x08GetItems\x12\x18.catalog.GetItemsRequest\x1a\x19.catalog.GetItemsResponse\x12N\n\rValidateItems\x12\x1d.catalog.ValidateItemsRequest\x1a\x1e.catalog.ValidateItemsResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "catalog_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_GETITEMREQUEST"]._serialized_start = 26
    _globals["_GETITEMREQUEST"]._serialized_end = 59
    _globals["_GETITEMSREQUEST"]._serialized_start = 61
    _globals["_GETITEMSREQUEST"]._serialized_end = 96
    _globals["_VALIDATEITEMSREQUEST"]._serialized_start = 98
    _globals["_VALIDATEITEMSREQUEST"]._serialized_end = 138
    _globals["_ITEMRESPONSE"]._serialized_start = 141
    _globals["_ITEMRESPONSE"]._serialized_end = 358
    _globals["_GETITEMSRESPONSE"]._serialized_start = 360
    _globals["_GETITEMSRESPONSE"]._serialized_end = 439
    _globals["_ITEMVALIDATION"]._serialized_start = 441
    _globals["_ITEMVALIDATION"]._serialized_end = 527
    _globals["_VALIDATEITEMSRESPONSE"]._serialized_start = 529
    _globals["_VALIDATEITEMSRESPONSE"]._serialized_end = 598
    _globals["_CATALOGSERVICE"]._serialized_start = 601
    _globals["_CATALOGSERVICE"]._serialized_end = 821
# @@protoc_insertion_point(module_scope)
