# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import warnings

import grpc

import catalog_pb2 as catalog__pb2

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in catalog_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class CatalogServiceStub(object):
    """Catalog Service - provides item information to other services via gRPC"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetItem = channel.unary_unary(
            "/catalog.CatalogService/GetItem",
            request_serializer=catalog__pb2.GetItemRequest.SerializeToString,
            response_deserializer=catalog__pb2.ItemResponse.FromString,
            _registered_method=True,
        )
        self.GetItems = channel.unary_unary(
            "/catalog.CatalogService/GetItems",
            request_serializer=catalog__pb2.GetItemsRequest.SerializeToString,
            response_deserializer=catalog__pb2.GetItemsResponse.FromString,
            _registered_method=True,
        )
        self.ValidateItems = channel.unary_unary(
            "/catalog.CatalogService/ValidateItems",
            request_serializer=catalog__pb2.ValidateItemsRequest.SerializeToString,
            response_deserializer=catalog__pb2.ValidateItemsResponse.FromString,
            _registered_method=True,
        )


class CatalogServiceServicer(object):
    """Catalog Service - provides item information to other services via gRPC"""

    def GetItem(self, request, context):
        """Get a single item by ID"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetItems(self, request, context):
        """Get multiple items by IDs (batch request)"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ValidateItems(self, request, context):
        """Check if items exist and are active"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_CatalogServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetItem": grpc.unary_unary_rpc_method_handler(
            servicer.GetItem,
            request_deserializer=catalog__pb2.GetItemRequest.FromString,
            response_serializer=catalog__pb2.ItemResponse.SerializeToString,
        ),
        "GetItems": grpc.unary_unary_rpc_method_handler(
            servicer.GetItems,
            request_deserializer=catalog__pb2.GetItemsRequest.FromString,
            response_serializer=catalog__pb2.GetItemsResponse.SerializeToString,
        ),
        "ValidateItems": grpc.unary_unary_rpc_method_handler(
            servicer.ValidateItems,
            request_deserializer=catalog__pb2.ValidateItemsRequest.FromString,
            response_serializer=catalog__pb2.ValidateItemsResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "catalog.CatalogService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("catalog.CatalogService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class CatalogService(object):
    """Catalog Service - provides item information to other services via gRPC"""

    @staticmethod
    def GetItem(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/catalog.CatalogService/GetItem",
            catalog__pb2.GetItemRequest.SerializeToString,
            catalog__pb2.ItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetItems(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/catalog.CatalogService/GetItems",
            catalog__pb2.GetItemsRequest.SerializeToString,
            catalog__pb2.GetItemsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ValidateItems(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/catalog.CatalogService/ValidateItems",
            catalog__pb2.ValidateItemsRequest.SerializeToString,
            catalog__pb2.ValidateItemsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
